name: Security Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hello-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "CI pipeline is alive"

  sast-scan:
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep OSS Scan
        run: semgrep scan --config p/default --error
